name: C/C++ CI

on:
  push:
    branches: [ "main" ]
    paths:
      - "hello.c"
  

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: chmod +x build.sh
        run: |
          chmod +x build.sh
        
      - name: gcc build
        run: |
          ./build.sh

      - name: update artifact
        uses: actions/upload-artifact@v3
        with:
          name: hello
          path: hello